=== apache/commons-configuration/src/test/resources/testMultiConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="configuration" type="configurationType"/>
  <xs:complexType name="configurationType">
    <xs:sequence>
      <xs:element type="colorsType" name="colors" minOccurs="0"/>
      <xs:element type="xs:integer" name="rowsPerPage" minOccurs="0"/>
      <xs:element type="buttonsType" name="buttons" minOccurs="0"/>
      <xs:element type="numberFormatType" name="numberFormat" minOccurs="0"/>
      <xs:element type="splitType" name="split" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Comma delimited lists</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="ChannelsType" name="Channels" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="splitType">
    <xs:sequence>
      <xs:element type="xs:string" name="list1" minOccurs="0"/>
      <xs:element type="xs:string" name="list2" minOccurs="0"/>
      <xs:element type="list3Type" name="list3" minOccurs="0"/>
      <xs:element type="list4Type" name="list4" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="colorsType">
    <xs:sequence>
      <xs:element type="xs:string" name="background" minOccurs="0"/>
      <xs:element type="xs:string" name="text" minOccurs="0"/>
      <xs:element type="xs:string" name="header" minOccurs="0"/>
      <xs:element type="linkType" name="link" minOccurs="0"/>
      <xs:element type="xs:string" name="default" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="list4Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="values"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="linkType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="normal"/>
        <xs:attribute type="xs:string" name="visited"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="list3Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="values"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="buttonsType">
    <xs:sequence>
      <xs:element type="xs:string" name="name" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="numberFormatType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="pattern"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ChannelType">
    <xs:sequence>
      <xs:element name="Name" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ChannelData" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="MoreChannelData" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ChannelsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="ChannelType" name="Channel" minOccurs="0"/>
    </xs:choice>
  </xs:complexType>
</xs:schema>

=== apache/commons-configuration/src/test/resources/testMultiConfiguration_3001.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://commons.apache.org/testMultiConfiguration.xsd">
  <colors>
    <background>#808080</background>
    <text>#000000</text>
    <header>#008000</header>
    <link normal="#000080" visited="#800080"/>
    <default>${colors.header}</default>
  </colors>
  <rowsPerPage>15</rowsPerPage>
  <buttons>
    <name>OK,Cancel,Help</name>
  </buttons>
  <numberFormat pattern="###\,###.##"/>
  <Channels>
    <Channel id="1">
      <Name>My Channel</Name>
    </Channel>
    <Channel id="2">
      <MoreChannelData>more test 2 data</MoreChannelData>
    </Channel>
  </Channels>
</configuration>

=== apache/commons-configuration/src/test/resources/testMultiConfiguration_2002.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<configuration
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://commons.apache.org/testMultiConfiguration.xsd">
  <colors>
    <background>#2222222</background>
    <text>#000000</text>
    <header>#222222</header>
    <link normal="#020202" visited="#202020"/>
    <default>${colors.header3}</default>
  </colors>
  <rowsPerPage>25</rowsPerPage>
  <buttons>
    <name>OK-2,Cancel-2,Help-2</name>
  </buttons>
  <numberFormat pattern="###\,###.##"/>
</configuration>

=== apache/commons-configuration/src/test/resources/testMultiDynamic_default.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://commons.apache.org/testMultiConfiguration.xsd">
  <colors>
    <background>#40404040</background>
    <text>#000000</text>
    <header>#444444</header>
    <link normal="#040404" visited="#404040"/>
    <default>${colors.default}</default>
  </colors>
  <Product>
    <FIIndex>
        <FI id="123456781">ID0001</FI>
        <FI id="AUTO01">IDAUTO01</FI>
        <FI id="AUTO02">IDAUTO02</FI>
    </FIIndex>
  </Product>
  <rowsPerPage>50</rowsPerPage>
  <buttons>
    <name>OK-4,Cancel-4,Help-4</name>
  </buttons>
  <numberFormat pattern="###\,###.##"/>
  <!-- Comma delimited lists -->
  <split>
    <list1>a,b,c</list1>
    <list2>a\,b\,c</list2>
    <list3 values="a,b,c"/>
    <list4 values="a\,b\,c"/>
  </split>
  <Channels>
    <Channel id="1">
      <Name>Channel 1</Name>
      <ChannelData>test 1 data</ChannelData>
    </Channel>
    <Channel id="2">
      <Name>Channel 2</Name>
      <ChannelData>test 2 data</ChannelData>
    </Channel>
  </Channels>
</configuration>
