<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<!--
  This is an invalid XML document, it does not conform to the declared DTD
  (a type is missing in one field element). This document is used for testing
  XMLConfiguration with a validating parser. It should be possible to load
  it if validation is disabled, but if validation is enabled, an exception
  should be thrown.
-->
<!DOCTYPE database [
<!ELEMENT database (table+)>
<!ELEMENT table (name, fields)>

<!ELEMENT fields (field+)>
<!ELEMENT field (name, type)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
]>
<database>
  <table>
    <name>customers</name>
    <fields>
      <field>
        <name>custID</name>
        <type>java.lang.Long</type>
      </field>
      <field>
        <name>custName</name>
      </field>
    </fields>
  </table>
</database>