<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<!--
  A valid XML document according to its DTD.
-->
<!DOCTYPE database [
<!ELEMENT database (table+)>
<!ELEMENT table (name, fields)>

<!ELEMENT fields (field+)>
<!ELEMENT field (name, type)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
]>

<database>
  <table>
    <name>customers</name>
    <fields>
      <field>
        <name>custID</name>
        <type>java.lang.Long</type>
      </field>
      <field>
        <name>custName</name>
        <type>java.lang.String</type>
      </field>
    </fields>
  </table>
</database>